### ISSUE TITLE
BUG ( switch key ) Uploader can't change GDSA / stucks on GDSA1 < NO switch to next key

### ISSUE THREAD

**Issue by RedBull01** [dockserver/container#61]
Hi All.

IDK why. He stuck on GDSA1 and can't change.
[https://ibb.co/SXJt3XK](url)

No error in: docker logs -f uploader
```json
Ozark (2017) - S04E03.mkv.json:
{
"filedir": "Tdrive/02-English/02-Tv Shows/01-Lite/01-Web/Ozark (2017)/Season 04",
"filebase": "Ozark (2017) - S04E03.mkv",
"filesize": " 3.0GiB",
"logfile": "/system/uploader/logs/Ozark (2017) - S04E03.mkv.txt",
"gdsa": "GDSA1"
}
```

If i stop uploader. Rename any GDSA for GDSA1 for change the actual GDSA1. Start Uploader. He work good.

Thx For help.

**Comment by RedBull01** [comment]
Hi. Idk why. My issue is deleted.

**Comment by doob187** [comment]
It's not delete... it was moved 

FROM dockserver to container

**Comment by doob187** [comment]
So the logic is now simpler and more effectively 

It's used randomly a key 

It's used the ARRAY ( maximum used key )  + 1 

Plus 1 means ( key from 1 > till ARRAY  ) 

all the possible bugs are now fixed

**Comment by RedBull01** [comment]
From Discord:

hi all. Can we talk about Uploader? I install the last version. and now:
GDSA swich all the time
Now have GDSA0 and not upload correctly. I rename my last GDSA (for me GDSA3 for GDSA0)
hope will be fine

Picture before rename GDSA3 for GDSA0
![image](https://user-images.githubusercontent.com/47831034/151583921-e1f82bf3-df8f-44c5-ad45-a963caf51081.png)

Picture after rename GDSA3 for GDSA0
![image](https://user-images.githubusercontent.com/47831034/151583973-80c80e42-ace8-4a6c-8f57-04746b505bed.png)

before everything. 
I use GDSA1, GDSA2, GDSA3.
I remove Uploader and delete the folder before he stuck on GDSA1
I re-install Uploader:latest
and upload only on GDSA1 and GDSA2 and never on GDSA3 but on GDSA0 and take 6sec for 30gb file. So problem.
stop uploader
rename GDSA3 to GDSA0
work good for now

**Comment by doob187** [comment]
https://github.com/dockserver/container/commit/b5e41e97d0d95d2a9a1e1243f7ccee48f89a6c3a

**Comment by doob187** [comment]
Can be closed now 

The randomly key is not used  KEY0 not anymore
