### ISSUE TITLE
Uploader not removing files

### ISSUE THREAD

**Issue by mrfret** [dockserver/container#67]
Latest uploader works but leaves files in /mnt/downloads/Media/whatever after transfer to Shared Drive. Files are in both locations. This doesn't happen with backups folder.

**Comment by doob187** [comment]
It will  fix them ASAP 

Deployed  mount from which date ,?!

**Comment by Indochild56** [comment]
the 27th

**Comment by mrfret** [comment]
> It will fix them ASAP
> 
> Deployed mount from which date ,?!

Just today for mine. Latest mount and uploader on test server

**Comment by doob187** [comment]
It's not the uploader 

It's the mount   they didn't nit used user 1000 
So the owners  right goes to root and uploader runs as  1000

1000 user can't remove files when it owned by root

**Comment by mrfret** [comment]
I thought a fresh install of latest mount/uploader automatically set perms for user 1000

**Comment by doob187** [comment]
Ya I have  fix them 

https://github.com/dockserver/container/commit/b9a39aa34dbc19f9e1aabd7fc691f0a17be4ef7d

https://github.com/dockserver/container/commit/467daa960494f0eb02fb682f80453f5c56b461a0

**Comment by mrfret** [comment]
I cannot get mount to finish deploying now

**Comment by doob187** [comment]
It's Fixing the permissions on the local drives 

This could take a long time ..

**Comment by doob187** [comment]
https://github.com/dockserver/container/commit/467daa960494f0eb02fb682f80453f5c56b461a0

Hare is the line

**Comment by mrfret** [comment]
IDK. I've left it running for the last hour or more and no change. I'll take another look tho.

**Comment by doob187** [comment]
https://github.com/orgs/dockserver/packages/container/docker-mount/14088342?tag=467daa96

You can also try this tag

**Comment by mrfret** [comment]
Trying that tag now

**Comment by mrfret** [comment]
OK that tag worked just fine.

**Comment by doob187** [comment]
Latest did not work ?! 

```sh
ls -la /mnt
```

This will show how owned the folders

**Comment by mrfret** [comment]
No I just stopped all the Arrs and sab and tried latest again. Still hangs. But madmaximus said it works for him. All owned by 1000 also,

**Comment by doob187** [comment]
3 deployed on differential Server 
No fails

**Comment by mrfret** [comment]
I'm sure it's just me, but I can't figure out why.

**Comment by mrfret** [comment]
Ok it finally worked. Started at 22:41:41 and finished at 01:14:20! That's crazy but it did work with latest.

**Comment by doob187** [comment]
okay crazy
Issue  please closing when it's worked

**Comment by mrfret** [comment]
Double checked and all is working. Thanks!

**Comment by mrfret** [comment]
So I may be wrong. I reinstalled uploader from ds menu. Everything worked. It deleted to files that had been left. But when I downloaded a new season to test, it uploaded, but did not delete the files in downloads again. I've left it alone for about an hour and still there. I didn't change anything at all on this test system so not sure what is going on.

**Comment by doob187** [comment]
I know you using shortcuts  between the drivers 
This could much a different 

Till now its just you that repost this 

We used rclone  union over rclone  rc command

Between  mergerfs  + rclone  union  is this a big difference 

1. Merger + Rclone:  
Mergerfs ( local )  + rclone  union  ( remote ) = 2 layer // 
remote + download s = unionfs 

1. Without  mergerfs: 
Rclone union ( remote + local ) = 1 layer  //
remote + download s = unionfs

Idk it will support  your shortcut system between the drives anymore

**Comment by madmaximus00** [comment]
There are three of us experiencing this, I don't know what shortcuts you're talking about. Everyone else seems to be not updated. My files also stopped being deleted after move this morning after it was working all day yesterday.

**Comment by madmaximus00** [comment]
did a command to change the permissions on /mnt/downloads then restarted uploader and it started uploading and deleting them again.  not sure what's happening to cause it to remove the permission to stop the deleting after a few hours

**Comment by doob187** [comment]
Set owner over the arrs  under 

Settings >
Media Management  >
[ show hidden ] 
>
![Screenshot_20220130-190649_Chrome](https://user-images.githubusercontent.com/60312740/151711723-36fd183f-e6bc-4147-8acc-cca796e59253.jpg)

**Comment by mrfret** [comment]
> I know you using shortcuts between the drivers This could much a different
> 
> Till now its just you that repost this
> 
> We used rclone union over rclone rc command
> 
> Between mergerfs + rclone union is this a big difference
> 
>     1. Merger + Rclone:
>        Mergerfs ( local )  + rclone  union  ( remote ) = 2 layer //
>        remote + download s = unionfs
> 
>     2. Without  mergerfs:
>        Rclone union ( remote + local ) = 1 layer  //
>        remote + download s = unionfs
> 
> 
> Idk it will support your shortcut system between the drives anymore

This is a test system. No shortcuts at all. 1 Team Drive. Setting chown group to 1000 in Arrs fixed the issue.
