### ISSUE TITLE
Master(%)

### ISSUE THREAD

**Issue by doob187** [dockserver/container#98]
Versuch Ibracorp nun ein shell docker appinstall Part??

Das Teil sieht mehr als ugly aus

Allein das es shell ist und die Pfade direkt auf appdata gehen bei opt ist schon sehr seltsam

**Comment by drag0n141** [comment]
Was von denen meinst du? Hab mir nicht angeschaut was die anderen so machen 😂

**Comment by doob187** [comment]
https://github.com/ibracorp/ibramenu

**Comment by drag0n141** [comment]
Ja die ganzen Files sehen schon echt schlimm aus, die Docker-Compose einfach da mit rein geschrieben 😂

**Comment by doob187** [comment]
Hast du Dropbox uploader / mount hinzugefügt?
Und der läuft auch??

**Comment by drag0n141** [comment]
Im Mount sollte es sowieso laufen da muss man nur die rclone.conf rein packen :) und im Uploader hab ich es getestet das läuft :)

**Comment by drag0n141** [comment]
Im Uploader hab ich auch mit und ohne Encrypt getestet hat beides ohne Probleme hochgeladen und war danach auch zu sehen :)

**Comment by drag0n141** [comment]
![image](https://user-images.githubusercontent.com/44865095/209788392-a0334ee0-8b57-42b5-b905-dc8488775e56.png)

**Comment by doob187** [comment]
Nicht schlecht 

Mit der db ist auch Geile Aktion

**Comment by drag0n141** [comment]
Ja wollte eigentlich auch die Keys und das used File in die DB auslagern, bin da noch im Test. Aber so wie es scheint ist das zu viel lesen und schreiben in die Datenbank und dann kommt die manchmal nicht mehr nach.

**Comment by doob187** [comment]
Dann wieder die Db langsam  ??
Oder hängt die sich dann auf ?

**Comment by drag0n141** [comment]
Ne z.B. werden dann laufende Uploads nicht mehr raus gelöscht, sobald auf die Datenbank geschrieben wird ist die Locked. Wenn das zu lange dauert wird der andere Schreibvorgang irgendwann verworfen.

**Comment by doob187** [comment]
Ah overflow von der db
Das natürlich doof dann

Aber wie es ist , ist es doch gut mit der db


Durch die db kann man es natürlich recht einfach dann halten 

Ist es eine SQL Datenbank  ?

Hab erlich nicht so geguckt gerade

**Comment by drag0n141** [comment]
Ja von den jetzigen Funktionen passt es. Aber sonst könnte man easy aufm WebUi den Used Wert z.B. anzeigen. Ist ne Sqlite Datenbank 😊

**Comment by doob187** [comment]
Ach das meinst du mir used 

Pro key das er es anzeigt

722 / 748 GB als Anzeige zb

**Comment by drag0n141** [comment]
Ja genau die Files im .keys Ordner. Aber da teste ich einfach etwas weiter ob ich es noch mehr optimiert bekomme 😊

**Comment by doob187** [comment]
rclone rc core/stats

Denn kann man dafür nutzen 

Dafür müsste aber alles über 

Rclone rc umgeschrieben werden

**Comment by drag0n141** [comment]
Hab ich probiert das funktioniert beim Upload nicht so gut. Gibt dann keine Prozente beim Upload und gab Probleme mit dem Key Wechsel 😅

**Comment by drag0n141** [comment]
Und wenn ich es über rclone RC Stats machen ist es ja auch nicht direkt in der Datenbank fürs WebUi 😅
